tables_id = {"Trabajadores"               : "tblNBHV9KDGDQNs8y",
             "Roles"                      : "tblk2itGEWE7ePo73",
             "Tecnologías"                : "tblXhF1lZUBKiNixP",
             "Competencias técnicas"      : "tblLUDGmhm7otZhGp",
             "Competencias blandas"       : "tblvuUUjjnUvdS1z1",
             "Certificaciones"            : "tblUforpTYin3pEZs",
             "Formulario certificaciones" : "tblERjkIA64JGPgNW",
             "Pruebas técnicas"           : "tblGy8pLPexkcpJcq",
             "Verticales"                 : "tblDZzmvFmWfMbmx5",
             "Assessment MAPFRE"          : "tbl7EYNl618IhKAse",
             "Data blandas"               : "tblImXJh9fSnqrW8B",
             "Data Competencias técnicas" : "tbl1kSY13iQhxi1O3",
             "Data Tecnologías"           : "tblca2y3nQTUPrbfx"}